Create 7-highlander

diff --git a/0x05-processes_and_signals/7-highlander b/0x05-processes_and_signals/7-highlander
--- a/0x05-processes_and_signals/7-highlander
+++ b/0x05-processes_and_signals/7-highlander
@@ -1,20 +1,17 @@
 #!/usr/bin/env bash
-# A Bash script that stops the 7-highlander process
-
-PID=$(pgrep -f 7-highlander)
-if [ -n "$PID" ]; then
-  kill "$PID"
-  echo "Process $PID signaled"
-else
-  echo "Process not found"
-fi
-
-#!/usr/bin/env bash
 # A Bash script that displays "To infinity and beyond" and handles SIGTERM
-
-trap 'echo "I am invincible!!!"' SIGTERM
-
+trap 'echo "OK"' SIGTERM
 while true; do
   echo "To infinity and beyond"
   sleep 2
 done
+
+
+#!/usr/bin/env bash
+# A Bash script that stops the 7-highlander process
+PID=$(pgrep -f 7-highlander)
+if [ -n "$PID" ]; then
+  kill "$PID"
+else
+  echo "Process not found"
+fi
